from typing import NamedTuple


class Language(NamedTuple):
    label: str
    ocr_code: str


SUPPORTED_LANGUAGES = {
    "ch": Language("CHINESE", "ch"),
    "zh": Language("CHINESE", "ch"),
    "en": Language("ENGLISH", "en"),
    "fr": Language("FRENCH", "fr"),
    "de": Language("GERMAN", "de"),
    "ko": Language("KOREAN", "korean"),
    "kr": Language("KOREAN", "korean"),
    "af": Language("AFRIKAANS", "af"),
    "it": Language("ITALIAN", "it"),
    "es": Language("SPANISH", "es"),
    "bs": Language("BOSNIAN", "bs"),
    "pt": Language("PORTUGUESE", "pt"),
    "pt-BR": Language("BRAZILIAN PORTUGUESE", "pt"),
    "cs": Language("CZECH", "cs"),
    "cy": Language("WELSH", "cy"),
    "da": Language("DANISH", "da"),
    "et": Language("ESTONIAN", "et"),
    "ga": Language("IRISH", "ga"),
    "hr": Language("CROATIAN", "hr"),
    "uz": Language("UZBEK", "uz"),
    "ru": Language("RUSSIAN", "ru"),
    "uk": Language("UKRAINIAN", "uk"),
    "el": Language("GREEK", "el"),
    "ku": Language("KURDISH", "ku"),
    "mt": Language("MALTESE", "mt"),
    "ro": Language("ROMANIAN", "ro"),
    "fi": Language("FINNISH", "fi"),
    "gl": Language("GALICIAN", "gl"),
    "rm": Language("ROMANSH", "rm"),
    "ca": Language("CATALAN", "ca"),
    "qu": Language("QUECHUA", "qu"),
    "te": Language("TELUGU", "te"),
    "sr-Cyrl": Language("SERBIAN CYRILLIC", "rs_cyrillic"),
    "bg": Language("BULGARIAN", "bg"),
    "mn": Language("MONGOLIAN", "mn"),
    "ab": Language("ABKHAZ", "ab"),
    "ady": Language("ADYGHE", "ady"),
    "kbd": Language("KABARDIAN", "kbd"),
    "av": Language("AVAR", "av"),
    "dar": Language("DARGWA", "dar"),
    "inh": Language("INGUSH", "inh"),
    "ce": Language("CHECHEN", "ce"),
    "lki": Language("LAK", "lki"),
    "lez": Language("LEZGIAN", "lez"),
    "tab": Language("TABASARAN", "tab"),
    "kk": Language("KAZAKH", "kk"),
    "ky": Language("KYRGYZ", "ky"),
    "tg": Language("TAJIK", "tg"),
    "mk": Language("MACEDONIAN", "mk"),
    "tt": Language("TATAR", "tt"),
    "cv": Language("CHUVASH", "cv"),
    "ba": Language("BASHKIR", "ba"),
    "mhr": Language("MARI", "mhr"),
    "mo": Language("MOLDOVAN", "mo"),
    "udm": Language("UDMURT", "udm"),
    "kv": Language("KOMI", "kv"),
    "os": Language("OSSETIAN", "os"),
    "bua": Language("BURIAT", "bua"),
    "xal": Language("KALMYK", "xal"),
    "tyv": Language("TUVINIAN", "tyv"),
    "sah": Language("SAKHA", "sah"),
    "kaa": Language("KARAKALPAK", "kaa"),
    "ar": Language("ARABIC", "ar"),
    "fa": Language("PERSIAN", "fa"),
    "ug": Language("UYGHUR", "ug"),
    "ur": Language("URDU", "ur"),
    "ps": Language("PASHTO", "ps"),
    "sd": Language("SINDHI", "sd"),
    "bal": Language("BALOCHI", "bal"),
    "hi": Language("HINDI", "hi"),
    "mr": Language("MARATHI", "mr"),
    "ne": Language("NEPALI", "ne"),
    "bh": Language("BIHARI", "bh"),
    "mai": Language("MAITHILI", "mai"),
    "ang": Language("OLD ENGLISH", "ang"),
    "bho": Language("BHOJPURI", "bho"),
    "mah": Language("MAGAHI", "mah"),
    "sck": Language("SADRI", "sck"),
    "new": Language("NEWAR", "new"),
    "gom": Language("KONKANI", "gom"),
    "sa": Language("SANSKRIT", "sa"),
    "bgc": Language("HARYANVI", "bgc"),
    "ta": Language("TAMIL", "ta"),
    "hu": Language("HUNGARIAN", "hu"),
    "sr-Latn": Language("SERBIAN LATIN", "rs_latin"),
    "id": Language("INDONESIAN", "id"),
    "oc": Language("OCCITAN", "oc"),
    "is": Language("ICELANDIC", "is"),
    "lt": Language("LITHUANIAN", "lt"),
    "mi": Language("MAORI", "mi"),
    "ms": Language("MALAY", "ms"),
    "nl": Language("DUTCH", "nl"),
    "no": Language("NORWEGIAN", "no"),
    "pl": Language("POLISH", "pl"),
    "sk": Language("SLOVAK", "sk"),
    "sl": Language("SLOVENIAN", "sl"),
    "sq": Language("ALBANIAN", "sq"),
    "sv": Language("SWEDISH", "sv"),
    "sw": Language("SWAHILI", "sw"),
    "tl": Language("TAGALOG", "tl"),
    "tr": Language("TURKISH", "tr"),
    "la": Language("LATIN", "la"),
    "be": Language("BELARUSIAN", "be"),
    "th": Language("THAI", "th"),
    "az": Language("AZERBAIJANI", "az"),
    "lv": Language("LATVIAN", "lv"),
    "pi": Language("PALI", "pi"),
    "vi": Language("VIETNAMESE", "vi"),
    "eu": Language("BASQUE", "eu"),
    "lb": Language("LUXEMBOURGISH", "lb"),
    # Latin-script languages not in PaddleOCR's official list; "es" is a placeholder that maps to the latin model.
    "jv": Language("JAVANESE", "es"),
    "ha": Language("HAUSA", "es"),
    "yo": Language("YORUBA", "es"),
    "su": Language("SUNDANESE", "es"),
    "om": Language("OROMO", "es"),
    "ig": Language("IGBO", "es"),
    "mg": Language("MALAGASY", "es"),
    "ceb": Language("CEBUANO", "es"),
    "so": Language("SOMALI", "es"),
    "mad": Language("MADURESE", "es"),
    "ht": Language("HAITIAN CREOLE", "es"),
    "zu": Language("ZULU", "es"),
    "ilo": Language("ILOCANO", "es"),
    "sn": Language("SHONA", "es"),
    "hil": Language("HILIGAYNON", "es"),
    "xh": Language("XHOSA", "es"),
    "tk": Language("TURKMEN", "es"),
}